language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t npnkha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true npnkha/docker-react npm run test